### PR TITLE
sound/pipewire: destroy multiple pipewire streams that are not destroyed

### LINKED ISSUE #490: [sound] creation of multiple streams that are not destroyed
The regular PCM command lifecycle for playing a stream is SET_PARAMS -> PREPARE -> START -> STOP ->RELEASE -> SET_PARAMS-> PREPARE -> ..........
but there are some exceptional cases that do not follow the regular PCM command lifecycle, like in the case of using sox tool to play audio from the guest, to test this:
start the vhost-device-sound daemon on the host with pipewire backend option enabled and enable rust debug on the daemon
Install sox tool on the guest and run play /usr/share/sounds/alsa/Front_Left.wav from the guest.
The order of PCM commands using this tool is SET_PARAMS -> PREPARE -> SET_PARAMS -> PREPARE -> SET_PARAMS -> PREPARE -> START -> STOP ->RELEASE -> .........
This order of PCM commands is also valid sequence of commands however this scenario lead to multiple creation of pipewire streams that are not destroyed. We need to ensure that in a case like this, when the prepare fn() in the pipewire backend is called multiple times without the release fn(), there should be only one pipewire stream. 

see https://github.com/virtio-sound/vhost-device/issues/43

### PR DESCRIPTION
**Pull request by dorindabassey**
### Summary of the PR

The PCM command transition prepare->prepare or set_param->prepare is allowed by the specification. however this type of transition in pipewire lead to multiple creation of pipewire streams that are not destroyed. This PR ensures that in a case like this, when the prepare fn() in the pipewire backend is called multiple times without the release fn(), there should be only one pipewire stream.

Close #490

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

File: vhost-device-sound/src/audio_backends/pipewire.rs [hunk 1]
```diff
@@ -208,6 +208,12 @@ impl AudioBackend for PwBackend {
 
             let params = &stream_params[stream_id as usize].params;
 
+            if let Some(stream) = stream_hash.get(&stream_id) {
+                stream.disconnect().expect("could not disconnect stream");
```
Comment (epilys) [inline vhost-device-sound/src/audio_backends/pipewire.rs:212]: Is panicking here instead of returning an error on purpose? (Is this error unrecoverable?)

**Comment by MatiasVara** [comment]
LGTM. I also wonder if panicking is the correct behavior when it is not possible to disconnect.

File: vhost-device-sound/src/audio_backends/pipewire.rs (hunk 1 above)
Comment (dorindabassey) [reply vhost-device-sound/src/audio_backends/pipewire.rs:212]: right, I think returning an error instead is better.

File: vhost-device-sound/src/lib.rs [hunk 2]
```diff
@@ -183,6 +183,8 @@ pub enum Error {
     StreamWithIdNotFound(u32),
     #[error("Channel number not supported: {0}")]
     ChannelNotSupported(u8),
+    #[error("Could not disconnect stream")]
+    CouldNotDisconnectStream,
```
Comment (epilys) [inline vhost-device-sound/src/lib.rs:187]: Better put this in `stream::Error` since it exists already, instead of making this enum bigger:

https://github.com/dorindabassey/vhost-device/blob/1809dae37c873589e4954ab0fd24197b3080e30d/vhost-device-sound/src/stream.rs#L13-L24

**Review by epilys — CHANGES_REQUESTED** [review]

File: vhost-device-sound/src/audio_backends/pipewire.rs [hunk 3]
```diff
@@ -208,6 +208,15 @@ impl AudioBackend for PwBackend {
 
             let params = &stream_params[stream_id as usize].params;
 
+            if let Some(stream) = stream_hash.get(&stream_id) {
+                if let Err(err) = stream.disconnect() {
+                    log::error!("Stream {} disconnect {}", stream_id, err);
+                    return Err(Error::CouldNotDisconnectStream);
+                }
+                stream_hash.remove(&stream_id);
+                stream_listener.remove(&stream_id);
```
Comment (bilelmoussaoui) [inline vhost-device-sound/src/audio_backends/pipewire.rs:217]: Shouldn't the stream id be removed from those hashmaps even if it failed to disconnect?

Comment (dorindabassey) [reply vhost-device-sound/src/audio_backends/pipewire.rs:217]: WDYM? The stream id will be removed regardless of whether the disconnection was successful or not.

Comment (bilelmoussaoui) [reply vhost-device-sound/src/audio_backends/pipewire.rs:217]: Not really per your code as you would return an error and the code I commented won't be executed

**Review by epilys — DISMISSED** [review]

File: vhost-device-sound/src/audio_backends/pipewire.rs [hunk 4]
```diff
@@ -208,6 +208,16 @@ impl AudioBackend for PwBackend {
 
             let params = &stream_params[stream_id as usize].params;
 
+            if let Some(stream) = stream_hash.get(&stream_id) {
+                let disconnect_result = stream.disconnect();
+                stream_hash.remove(&stream_id);
+                stream_listener.remove(&stream_id);
+                if let Err(err) = disconnect_result {
```
Comment (epilys) [inline vhost-device-sound/src/audio_backends/pipewire.rs:215]: No real reason to bind the disconnect result. Just a nitpick and not a functional change, otherwise LGTM.

```suggestion   
                stream_hash.remove(&stream_id);
                stream_listener.remove(&stream_id);
                if let Err(err) = stream.disconnect() {
```

Comment (dorindabassey) [reply vhost-device-sound/src/audio_backends/pipewire.rs:215]: Here I think the order of operation is important, I want to disconnect the stream before removing it from the hashmap and stream_listener. so I'd prefer to leave it as it is.

Comment (stefano-garzarella) [reply vhost-device-sound/src/audio_backends/pipewire.rs:215]: @dorindabassey IIUC we acquired the write lock for both, so why the order is important?

Comment (epilys) [reply vhost-device-sound/src/audio_backends/pipewire.rs:215]: (It isn't important, and since those statements don't seem to have side effects to each other the compiler is actually within rights to re-order them as it pleases. Take this with a pinch of salt because I didn't actually check if that happens in this code.)

Comment (dorindabassey) [reply vhost-device-sound/src/audio_backends/pipewire.rs:215]: going by your suggestion @epilys the borrow checker complains ```error[E0502]: cannot borrow `stream_hash` as mutable because it is also borrowed as immutable
   --> vhost-device-sound/src/audio_backends/pipewire.rs:212:17
    |
211 |             if let Some(stream) = stream_hash.get(&stream_id) {
    |                                   ----------- immutable borrow occurs here
212 |                 stream_hash.remove(&stream_id);
    |                 ^^^^^^^^^^^ mutable borrow occurs here
213 |                 stream_listener.remove(&stream_id);
214 |                 if let Err(err) = stream.disconnect() {
    |                                   ------ immutable borrow later used here
``` which was why i left it this way.

**Review by stefano-garzarella — APPROVED** [review]
