### PR TITLE
vsock: Fix issues with sibling VM communication

### LINKED ISSUE #384: vsock: Issues in sibling VM communication
These issues were discovered while trying to test the current implementation of sibling VM communication in vhost-user-vsock. The testing was done with [iperf-vsock](https://github.com/stefano-garzarella/iperf-vsock) and [nc-vsock](https://github.com/stefanha/nc-vsock), both patched to set `.svm_flags = VMADDR_FLAG_TO_HOST`.

### Deadlock
If you try to test the sibling communication by running `iperf-vsock` or transferring big files with `nc-vsock`, the vhost-user-vsock process hangs and becomes completely irresponsive. After a bit of debugging, I discovered that there is deadlock.

The deadlock occurs when two sibling VMs simultaneously try to send each other packets. The `VhostUserVsockThread`s corresponding to both the VMs hold their own locks while executing `thread_backend.send_pkt` and then try to lock each other to access their counterpart's `raw_pkts_queue`. This ultimately results in a deadlock.

In particular, [this line of code](https://github.com/rust-vmm/vhost-device/blob/0bb783601eed58d1ed82bbb9acb23f5b8de73057/crates/vsock/src/thread_backend.rs#L182C1-L182C93) unleashes the deadlock.

The deadlock can be resolved by separating the mutex over `raw_pkts_queue` from the mutex over `VhostUserVsockThread`.

### Raw packets queue not being processed completely
Even after resolving the deadlock, the vhost-user-vsock process still hangs while testing, though not completely irresponsive this time. It turns out that sometimes the raw packets pending on the `raw_pkts_queue` are never processed, resulting in the hang.

This happens because currently, the `raw_pkts_queue` is processed only when a `SIBLING_VM_EVENT` is received. But it may happen that the `raw_pkts_queue` could not be processed completely due to insufficient space in the RX virtqueue at that time.

This can be resolved by trying to process raw packets on other events too similar to what happens in the RX of standard packets.

## Current status
While fixing the above two issues seems to make `nc-vsock` run flawlessly, testing with `iperf-vsock` still results in the vhost-user-vsock process hanging. There might be a notification problem and could be related to the `EVENT_IDX` feature.

### PR DESCRIPTION
**Pull request by techiepriyansh**
This PR attempts to resolve issues with sibling VM communication described in #384.
 
 Resolves partially  #384.

### CODE REVIEW

**Comment by techiepriyansh** [comment]
CI fails with `cargo audit`. Need to manually `cargo update` again.

**Comment by stefano-garzarella** [comment]
> CI fails with `cargo audit`. Need to manually `cargo update` again.

@vireshk is fixing that in #380, we can rebase on that after the merge ;-)

File: crates/vsock/src/vhu_vsock.rs [hunk 1]
```diff
@@ -316,8 +317,13 @@ impl VhostUserBackend<VringRwLock, ()> for VhostUserVsockBackend {
...
 
-        if device_event != EVT_QUEUE_EVENT && thread.thread_backend.pending_rx() {
-            thread.process_rx(vring_rx, evt_idx)?;
+        if device_event != EVT_QUEUE_EVENT {
+            if thread.thread_backend.pending_rx() {
+                thread.process_rx(vring_rx, evt_idx)?;
+            }
+            if thread.thread_backend.pending_raw_pkts() {
+                thread.process_raw_pkts(vring_rx, evt_idx)?;
+            }
```
Comment (stefano-garzarella) [inline crates/vsock/src/vhu_vsock.rs:326]: Now it seems we call `process_rx` and `process_raw_pkts` (also the pending ones) always together, so might it be better to unify them to avoid future problems?

Effectively rx now depends on both backend and siblings.

File: crates/vsock/src/main.rs [hunk 2]
```diff
@@ -181,10 +181,16 @@ pub(crate) fn start_backend_server(config: VsockConfig, cid_map: Arc<RwLock<CidM
...
+        {
+            let thread_lock = backend.threads[0].lock().unwrap();
+            cid_map.write().unwrap().insert(
+                config.get_guest_cid(),
+                (
+                    thread_lock.thread_backend.raw_pkts_queue.clone(),
+                    thread_lock.sibling_event_fd.try_clone().unwrap(),
+                ),
+            );
+        }
```
[the remark this answers is not in the document]
Comment (techiepriyansh) [reply crates/vsock/src/main.rs:193]: Right. Now that we are not storing a reference to the backend itself in the map, this should be the way to go.

**Comment by techiepriyansh** [comment]
Resolved starvation of the raw packets queue from the standard RX queue.

File: crates/vsock/src/vhu_vsock.rs (hunk 1 above)
Comment (techiepriyansh) [reply crates/vsock/src/vhu_vsock.rs]: We still need the function to process raw packets only when a `SIBLING_EVENT` is received. So, instead I have modified the logic here to prevent the starvation of one queue by another.

File: crates/vsock/src/vhu_vsock.rs [hunk 3]
```diff
@@ -317,8 +320,30 @@ impl VhostUserBackend<VringRwLock, ()> for VhostUserVsockBackend {
...
+                RxQueueType::RawPkts => {
+                    if thread.thread_backend.pending_rx() {
+                        thread.process_rx(vring_rx, evt_idx)?;
+                        *last_processed = RxQueueType::Standard;
+                    }
+                    if thread.thread_backend.pending_raw_pkts() {
+                        thread.process_raw_pkts(vring_rx, evt_idx)?;
+                    }
+                }
+            }
```
Comment (stefano-garzarella) [inline crates/vsock/src/vhu_vsock.rs:346]: What about moving this in `VhostUserVsockThread`?

I think we can also move `last_processed` there.
For now, we have a single thread that handles all the queue, in the future we can have multiple threads, but I'm expecting that one thread will always handle the same set of queues, so we shouldn't have multiple threads competing for the same queue.

**Review by stefano-garzarella — COMMENTED** [review]
LGTM, just a comment about rx handling

**Comment by stefano-garzarella** [comment]
Regarding issue #384, what things are missing that need to be resolved?

**Comment by techiepriyansh** [comment]
Moved the RX handling (queue switching on each iteration to prevent starvation) to `VhostUserVsockThread`.

**Comment by techiepriyansh** [comment]
> Regarding issue #384, what things are missing that need to be resolved?

Even with the fixes introduced this PR, iperf-vsock does not seem to work. Logging the packet traffic received by the vhost-user-vsock application reveals that after sending only a few RW packets, the client stops sending any more packets. Following could be the reasons for this problem: 
* There might be a notification problem inside the vhost-user-vsock application
* It could be due to the way iperf works internally
* It might have something to do with vsock credit updates

**Review by stefano-garzarella — APPROVED** [review]
LGTM!

Just a little thing if you want: I'd replace `process_standard_rx` with `process_unix_sockets`. We can also remove `pub` from it.

**Comment by stefano-garzarella** [comment]
Regarding issue #384, what things are missing that need to be resolved?

> > Regarding issue #384, what things are missing that need to be resolved?
> 
> Even with the fixes introduced in this PR, iperf-vsock does not seem to work. Logging the packet traffic received by the vhost-user-vsock application reveals that after sending only a few RW packets, the client stops sending any more packets. Following could be the reasons for this problem:
> 
>     * There might be a notification problem inside the vhost-user-vsock application
> 
>     * It could be due to the way iperf works internally
> 
>     * It might have something to do with vsock credit updates

Okay thanks! Can you update the issue with this information?

**Comment by techiepriyansh** [comment]
Done.

**Review by stefano-garzarella — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
@mathieupoirier @vireshk @stsquad can you take a look?
I think we should merge this before the v0.1.0 release.

**Review by vireshk — APPROVED** [review]
