### PR TITLE
vsock: fix use-after-close RawFd unsafe {} use

### LINKED ISSUE #232: Fix vsock test failure
while true; do RUST_BACKTRACE=1 cargo test vsock -- --test-threads=11 || break; done

makes it break.

Link to the discussion: https://github.com/rust-vmm/vhost-device/pull/230#issuecomment-1277175487

### PR DESCRIPTION
**Pull request by epilys**
### Summary of the PR
vsock tests could not be run in parallel because of seemingly unrelated crashes, as reported in #232. This PR fixes the bug and also adds a dev dependency to `tempfile` and creates a unique working directory for every test that was previously serialized.

Fixes #232.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

File: crates/vsock/src/thread_backend.rs [hunk 1]
```diff
@@ -307,11 +307,7 @@ impl VsockThreadBackend {
         self.backend_rxq
             .push_back(ConnMapKey::new(pkt.dst_port(), pkt.src_port()));
 
-        self.stream_map.insert(
-            stream_fd,
-            // SAFETY: Safe as the file descriptor is guaranteed to be valid.
```
Comment (Ablu) [inline crates/vsock/src/thread_backend.rs:312]: It does not immediately become clear to me what constraint was violated here. The docs of `from_raw_fd` also only state that "it should be valid", not that it must not be tied to another UnixStream instance? Or is that not a safety constraint, but a functional requirement (as in: "it won't crash, but also won't do what you want")?

Maybe some detail about this would be helpful in the commit message.

File: crates/vsock/src/main.rs [hunk 2]
```diff
@@ -287,116 +287,182 @@ mod tests {
...
+            assert_eq!(configs.len(), 1);
+
+            let config = &configs[0];
+            assert_eq!(config.get_guest_cid(), 3);
+            assert_eq!(config.get_socket_path(), socket_path);
+            assert_eq!(config.get_uds_path(), uds_path);
+            assert_eq!(config.get_tx_buffer_size(), 64 * 1024);
+        }
+
+        _ = test_dir.close();
```
Comment (Ablu) [inline crates/vsock/src/main.rs:312]: If we ignore the result anyway, is there any point in explicitly calling `.close()` here? If I understand it correctly, that only helps to assert that cleanup actually happened, but if we ignore the result, we do not do that? Does that maybe also allow to get rid of the extra nested scope?

File: crates/vsock/src/main.rs [hunk 3]
```diff
@@ -287,116 +287,182 @@ mod tests {
     }
 
     #[test]
-    #[serial]
     fn test_vsock_config_setup() {
-        let args = VsockArgs::from_args(3, "/tmp/vhost4.socket", "/tmp/vm4.vsock", 64 * 1024);
+        let test_dir = tempdir().expect("Could not create a temp test directory.");
+        std::env::set_current_dir(&test_dir).expect("Could not chdir to temp test directory.");
```
Comment (Ablu) [inline crates/vsock/src/main.rs:292]: Won't setting the cwd still race between the threads? Why is it needed now while it was not needed before?

File: crates/vsock/src/main.rs [hunk 4]
```diff
@@ -287,116 +287,182 @@ mod tests {
...
+            ];
+            let uds_paths = [
+                test_dir.path().join("vm3.vsock"),
+                test_dir.path().join("vm4.vsock"),
+                test_dir.path().join("vm5.vsock"),
+            ];
+            let params = format!(
+                "--vm socket={vhost3_socket},uds_path={vm3_vsock} \
+              --vm socket={vhost4_socket},uds-path={vm4_vsock},guest-cid=4,tx_buffer_size=65536 \
+              --vm guest-cid=5,socket={vhost5_socket},uds_path={vm5_vsock},tx-buffer-size=32768",
```
Comment (Ablu) [inline crates/vsock/src/main.rs:334]: this looks a bit weirdly aligned now.

File: crates/vsock/src/main.rs (hunk 3 above)
Comment (epilys) [reply crates/vsock/src/main.rs:292]: the dir returned by tempdir is unique, not shared between threads

File: crates/vsock/src/main.rs (hunk 4 above)
Comment (epilys) [reply crates/vsock/src/main.rs:334]: will fix!

File: crates/vsock/src/thread_backend.rs (hunk 1 above)
Comment (Ablu) [reply crates/vsock/src/thread_backend.rs:312]: Yeah, I just wonder why the safety requirement does not spell that out, but I assume it is because it does not cause any undefined behaviour but just causes undesired errors?

File: crates/vsock/src/main.rs (hunk 3 above)
Comment (Ablu) [reply crates/vsock/src/main.rs:292]: Well but `std::env::set_current_dir` will set the working directory for all threads at once, right? Also, it is not clear to me why `std::env::set_current_dir` was not required before but is now.

File: crates/vsock/src/main.rs (hunk 2 above)
Comment (epilys) [reply crates/vsock/src/main.rs:312]: It's there to prevent future rewrites from accidentally dropping `test_dir` earlier than it should. (The compiler would show "test_dir is already borrowed" or "has moved")

As for the error path, now that I think of it it should not ignore the `close()` error.

File: crates/vsock/src/main.rs (hunk 3 above)
Comment (epilys) [reply crates/vsock/src/main.rs:292]: Good point on the threads. I will remove it.

File: crates/vsock/src/thread_backend.rs (hunk 1 above)
Comment (epilys) [reply crates/vsock/src/thread_backend.rs:312]: Because that depends on the type implementing the trait, and in this case `UnixStream` assumes it owns the file descriptor.

File: crates/vsock/src/main.rs [hunk 5]
```diff
@@ -287,116 +287,182 @@ mod tests {
...
+            assert_eq!(config.get_tx_buffer_size(), 64 * 1024);
+        }
+
+        _ = test_dir.close();
     }
 
     #[test]
-    #[serial]
     fn test_vsock_config_setup_from_vm_args() {
-        let params = "--vm socket=/tmp/vhost3.socket,uds_path=/tmp/vm3.vsock \
```
Comment (stefano-garzarella) [inline crates/vsock/src/main.rs:310]: I honestly don't really like to change more than 500 lines just to indent by one block.

IIUC it's to clearly leave the creation of the temporary folder and chdir out of the test.
At this point how about a wrapper function for each test where we need to do it?

That way we minimize the changes.

**Comment by Ablu** [comment]
> vsock: use tempfile in tests
> Tests were run in a series before the previous commit, and masked a bug.
>
> Test files that refer to sockets need to be unique per test run. Since
> these tests create/use/free resources, they should take care not to
> litter /tmp/ and not share any file with other tests.
>
> Use a unique temp dir as a working directory in every run instead of
`/tmp/`.

I think the commit message needs an update now :). No working dir changes are done anymore.

File: crates/vsock/src/vhu_vsock_thread.rs [hunk 6]
```diff
@@ -705,7 +710,7 @@ mod tests {
         assert!(VhostUserVsockThread::epoll_register(
             epoll_fd,
             dummy_fd.as_raw_fd(),
-            epoll::Events::EPOLLOUT
+            epoll::Events::EPOLLOUT,
```
Comment (Ablu) [inline crates/vsock/src/vhu_vsock_thread.rs:713]: There seem to be some artifacts from the reformat left here. Would either drop them or move to a separate commit.

File: Cargo.lock [hunk 7]
```diff
@@ -1406,7 +1323,7 @@ dependencies = [
  "log",
  "serde",
  "serde_yaml",
- "serial_test",
```
[the remark this answers is not in the document]
Comment (Ablu) [reply Cargo.lock:1409]: I think this is still not mentioned? :thinking:

**Review by Ablu — COMMENTED** [review]
Some nit-picking, less indentation noise certainly helps :)

File: Cargo.lock (hunk 7 above)
[the remark this answers is not in the document]
Comment (epilys) [reply Cargo.lock:1409]: :D I rewrote it to make it more informative and standalone.

**Review by Ablu — APPROVED** [review]

**Comment by vireshk** [comment]
@stefano-garzarella looks okay to you now ? And thanks @epilys for fixing the long standing issue we couldn't fix earlier :)

File: crates/vsock/src/thread_backend.rs [hunk 8]
```diff
@@ -333,30 +329,39 @@ impl VsockThreadBackend {
...
+        let vsock_socket_path = test_dir
+            .path()
+            .join("test_vsock_thread_backend.vsock")
+            .display()
+            .to_string();
+        let vsock_peer_path = test_dir
+            .path()
+            .join("test_vsock_thread_backend.vsock_1234")
+            .display()
+            .to_string();
```
[the remark this answers is not in the document]
Comment (epilys) [reply crates/vsock/src/thread_backend.rs]: Removed, thanks!

File: crates/vsock/src/vhu_vsock_thread.rs (hunk 6 above)
Comment (epilys) [reply crates/vsock/src/vhu_vsock_thread.rs]: Removed, thanks!

File: crates/vsock/src/main.rs (hunk 5 above)
Comment (epilys) [reply crates/vsock/src/main.rs:310]: Removed, thanks!

File: crates/vsock/src/main.rs [hunk 9]
```diff
@@ -287,116 +287,182 @@ mod tests {
...
     #[test]
-    #[serial]
     fn test_vsock_config_setup() {
-        let args = VsockArgs::from_args(3, "/tmp/vhost4.socket", "/tmp/vm4.vsock", 64 * 1024);
+        let test_dir = tempdir().expect("Could not create a temp test directory.");
+        std::env::set_current_dir(&test_dir).expect("Could not chdir to temp test directory.");
 
-        let configs = Vec::<VsockConfig>::try_from(args);
-        assert!(configs.is_ok());
+        {
```
[the remark this answers is not in the document]
Comment (epilys) [reply crates/vsock/src/main.rs]: Removed, thanks!

**Review by stefano-garzarella — APPROVED** [review]

**Review by vireshk — APPROVED** [review]
